// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD64VGsdnjfg1gylbCwuV80lisO4ZZs7-w',
    appId: '1:52261670345:web:96957583a5fb677e262c18',
    messagingSenderId: '52261670345',
    projectId: 'code-x-novas',
    authDomain: 'code-x-novas.firebaseapp.com',
    storageBucket: 'code-x-novas.firebasestorage.app',
    measurementId: 'G-N2JKK4LZX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2cauoAvA2dEDbBHta0iXSn2zhNC4074I',
    appId: '1:52261670345:android:e4eb056be85acc80262c18',
    messagingSenderId: '52261670345',
    projectId: 'code-x-novas',
    storageBucket: 'code-x-novas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe5lO66wC3dC_NUShGBPcNKhaegNeOwuY',
    appId: '1:52261670345:ios:b7103f319157022d262c18',
    messagingSenderId: '52261670345',
    projectId: 'code-x-novas',
    storageBucket: 'code-x-novas.firebasestorage.app',
    iosBundleId: 'com.example.inoxNova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe5lO66wC3dC_NUShGBPcNKhaegNeOwuY',
    appId: '1:52261670345:ios:b7103f319157022d262c18',
    messagingSenderId: '52261670345',
    projectId: 'code-x-novas',
    storageBucket: 'code-x-novas.firebasestorage.app',
    iosBundleId: 'com.example.inoxNova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD64VGsdnjfg1gylbCwuV80lisO4ZZs7-w',
    appId: '1:52261670345:web:26ad93a1ded9c579262c18',
    messagingSenderId: '52261670345',
    projectId: 'code-x-novas',
    authDomain: 'code-x-novas.firebaseapp.com',
    storageBucket: 'code-x-novas.firebasestorage.app',
    measurementId: 'G-MD8N717YDQ',
  );
}
